name: Get latest release version
on:
  schedule:
    - cron: '* * * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Fetch release version
        run: |
          curl -O https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/NostalgiaForInfinityNext.py && \
          mv NostalgiaForInfinityNext.py user_data/strategies
          curl -O https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/NostalgiaForInfinityX.py && \
          mv NostalgiaForInfinityX.py user_data/strategies
          curl -O https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/configs/blacklist-binance.json && \
          mv blacklist-binance.json user_data
          curl -O https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/configs/pairlist-volume-binance-usdt.json && \
          mv pairlist-volume-binance-usdt.json user_data
          curl -O https://raw.githubusercontent.com/iterativv/NostalgiaForInfinity/main/configs/pairlist-volume-binance-busd.json && \
          mv pairlist-volume-binance-busd.json user_data
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'joaorafaelm'
          git config --global user.email 'joaoraf@me.com'
          git commit -am "New release version"
          git push

      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        if: steps.git-check.outputs.modified == 'true'
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: Config Files updated.
